export const categories = [
  { value: "programming_tech", label: "Programming & Tech"},
  { value: "graphics_design", label: "Graphics & Design" },
  { value: "digital_marketing", label: "Digital Marketing" },
  { value: "video_animation", label: "Video & Animation" },
  { value: "ai_services", label: "AI Services"},
  { value: "business", label: "Business"},
  { value: "writing_translation", label: "Writing & Translation"},
  { value: "consulting", label: "Consulting" },
];


export const servicesByCategory: { [key: string]: string[] } = {
  programming_tech: [
    "Front-end development (HTML, CSS, JavaScript, React, Angular, Vue.js)",
    "Back-end development (Node.js, Python, PHP, Ruby, Java)",
    "Full-stack development",
    "WordPress, Shopify, or other CMS development",
    "E-commerce website creation",
    "Web application development",
    "iOS app development (Swift, Objective-C)",
    "Android app development (Kotlin, Java)",
    "Cross-platform app development (Flutter, React Native)",
    "Custom software solutions",
    "Desktop application development",
    "API development and integration",
    "Database development (SQL, NoSQL, MongoDB, MySQL)",
    "2D/3D game development",
    "Unity or Unreal Engine development",
    "Mobile game development",
    "Cloud computing setup (AWS, Azure, Google Cloud)",
    "CI/CD pipeline setup",
    "Server management and configuration",
    "Penetration testing",
    "Network security",
    "IT consulting",
    "Data recovery",
    "Smart contract development",
    "NFT creation",
    "Cryptocurrency wallet development",
    "Website maintenance",
    "Bug fixing",
    "Technical support and troubleshooting",
    "Data scraping and web crawling",
    "Data visualization",
    "Machine learning model development",
    "Chatbot development",
    "IoT (Internet of Things) solutions",
    "Automation scripts (Python, Bash)",
  ],
  graphics_design: [
    "Logo design",
    "Brand identity creation (business cards, letterheads)",
    "Brand style guides",
    "UI/UX design",
    "Website mockups",
    "Mobile app interface design",
    "Social media graphics",
    "Banners and advertisements",
    "Infographics",
    "Brochures, flyers, and posters",
    "Custom illustrations",
    "Character design",
    "Digital art",
    "Concept art",
    "Book covers",
    "Packaging design",
    "Menu design",
    "T-shirt design",
    "Merchandise mockups",
    "3D modeling and rendering",
    "Product visualization",
    "Photo editing and retouching",
    "Presentation design",
    "Motion graphics",
  ],
  digital_marketing: [
    "On-page SEO",
    "Off-page SEO (link building)",
    "Technical SEO",
    "E-Commerce Marketing",
    "Keyword research",
    "Social media management (Facebook, Instagram, Twitter, LinkedIn)",
    "Ad campaign setup (Facebook Ads, Instagram Ads)",
    "Content creation for social media",
    "Blog management",
    "Email marketing campaigns",
    "Content strategy development",
    "Google Ads setup and management",
    "Bing Ads",
    "Retargeting campaigns",
    "Influencer outreach",
    "Campaign management",
    "Email template design",
    "Automation setup (Mailchimp, Klaviyo)",
    "Google Analytics setup",
    "Marketing funnel creation",
    "Conversion rate optimization (CRO)",
    "Affiliate marketing",
    "Local SEO",
    "Video ad creation",
  ],
  video_animation: [
    "Post-production editing",
    "Color grading",
    "Sound design",
    "2D animation",
    "3D animation",
    "Motion graphics",
    "Whiteboard animation",
    "Corporate videos",
    "Promotional videos",
    "Product demo videos",
    "Event videography",
    "Animated explainer videos",
    "Screencast tutorials",
    "Short-form video content (Reels, TikToks, YouTube Shorts)",
    "Video ads",
    "Drone videography",
    "Stop-motion animation",
    "Subtitling and captioning",
  ],
  ai_services: [
    "Model development (classification, regression, clustering)",
    "Deep learning (neural networks, CNNs, RNNs)",
    "Natural language processing (NLP)",
    "Chatbot development (conversational AI)",
    "AI integration into applications",
    "Computer vision solutions",
    "Predictive analytics",
    "Data preprocessing and cleaning",
    "AI-driven insights",
    "AI-powered workflow automation",
    "Robotic process automation (RPA)",
    "AI model training and optimization",
    "Custom AI algorithm development",
    "Voice recognition systems",
  ],
  business: [
    "Business plan writing",
    "Financial forecasting",
    "Pitch deck creation",
    "Shopify store setup",
    "Amazon seller account management",
    "Product listing optimization",
    "Administrative support",
    "Calendar management",
    "Data entry",
    "Customer service outsourcing",
    "Live chat support",
    "Bookkeeping",
    "Accounting",
    "Tax preparation",
    "Recruitment and talent sourcing",
    "HR policy development",
    "Market research",
    "Supply chain management",
    "CRM setup (HubSpot, Salesforce)",
  ],
  writing_translation: [
    "Blog writing",
    "Article writing",
    "Website content",
    "Product descriptions",
    "Ad copy",
    "Sales pages",
    "Email copy",
    "Fiction and non-fiction writing",
    "Scriptwriting",
    "Poetry",
    "Grammar and style editing",
    "Manuscript proofreading",
    "User manuals",
    "Whitepapers",
    "Documentation",
    "Document translation (e.g., English to Spanish, etc.)",
    "Website localization",
    "Subtitling and transcription",
    "Resume writing",
    "Cover letter writing",
    "Ghostwriting",
  ],
  consulting: [
    "Startup consulting",
    "Growth strategy",
    "Operational efficiency",
    "Digital marketing strategy",
    "Brand positioning",
    "Market entry strategy",
    "Investment advice",
    "Financial planning",
    "Budgeting and cost optimization",
    "Technology stack recommendations",
    "Cybersecurity consulting",
    "Cloud migration strategy",
    "Contract review",
    "Intellectual property advice",
    "Compliance consulting",
    "Employee training programs",
    "Organizational development",
    "Sustainability consulting",
    "Risk management",
    "Project management",
  ],
};